# Generated by Django 4.1.3 on 2023-06-09 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("c2_api_key", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "c2_refresh_key",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "c2_logbook_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("last_c2_sync", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=2)),
                ("description", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name_plural": "Club Role",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("squad_name", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("is_coach", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("f", "female"), ("m", "male"), ("o", "other")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("coached_by", models.ManyToManyField(blank=True, to="users.member")),
                ("role_code", models.ManyToManyField(blank=True, to="users.role")),
                (
                    "squad",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.squad",
                    ),
                ),
            ],
        ),
    ]
