# Generated by Django 4.1.3 on 2023-06-09 16:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinishedErg",
            fields=[
                (
                    "c2_logbook_id",
                    models.CharField(
                        blank=True, max_length=250, null=True, unique=True
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=5000, null=True),
                ),
                ("distance", models.PositiveIntegerField()),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "low"),
                            ("moderate", "moderate"),
                            ("intense", "intense"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("split_time", models.DurationField()),
                ("avg_spm", models.PositiveIntegerField(blank=True, null=True)),
                ("avg_heartrate", models.PositiveIntegerField(blank=True, null=True)),
                ("is_test", models.BooleanField(default=False)),
                ("completed_at", models.DateField()),
                ("result_time", models.DurationField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
