# Generated by Django 4.1.3 on 2023-06-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0001_initial"),
        ("logbook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finishederg",
            name="completed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.member",
            ),
        ),
    ]
